version: '3.3'
services:
  app:
    container_name: ${ALIAS}
    image: ${ALIAS}-image
    restart: always
    tty: true
    volumes:
      - ./data/conf.toml:/usr/project/conf.toml
    command: >
        bash -c "cd /usr/project && export TERM=xterm-256color && ./app"
